### ISSUE TITLE
FPU ops issues

### ISSUE THREAD

**Issue by ukasz** [tactcomplabs/rev#46]
We see basic problems with floating point operations.
To give an example, the following test fails on devel branch:
```
int main() {
        float z = 1;
        assert(z > 0);
}
```

**Comment by donofrio** [comment]
Issue was confirmed and reproduced. Fix implemented and this test should be working in the  latest devel branch

**Comment by ukasz** [comment]
We've seen it fixed on e285dff, but on latest devel it is still broken (FPU issues in general, not this particular test case).

**Comment by donofrio** [comment]
Can confirm we are still seeing that... root caused to an issue with FP MV, fix in place and will be included in devel shortly

**Comment by donofrio** [comment]
Additional FP op updates pushed to devel - test should be working

**Comment by ukasz** [comment]
This particular test case is fixed on (4414659), but we stil see FPU issues.
Example:
```
int main() {
        assert(fabs(-1) >= 1);
        assert(fabs(-1) < 1.01);
        return 0;
}
```
And something less trivial:
```
#include <cmath>
#define assert(x) if (!(x)) { asm(".byte 0x00"); asm(".byte 0x00"); asm(".byte 0x00"); asm(".byte 0x00"); }

template <typename T> void testPI()
{
        T pi = 0;
        T n = 1;

        for(int i = 0; i < 10000; i++, n += 2) {
                T tmp = 4.0 / n;
                if (i % 2)
                        pi -= tmp;
                else pi += tmp;
        }
        assert(pi > 3.1414);
        assert(pi < 3.1417);
}

int main() {
        testPI<float>();
}

```
Sqrt is a dedicated instruction, so we need a test for that as well:

```
#include <cmath>
#define assert(x) if (!(x)) { asm(".byte 0x00"); asm(".byte 0x00"); asm(".byte 0x00"); asm(".byte 0x00"); }

int main() {
        float fx, fy;
        double dx, dy;

        fx = 25;
        fy = sqrt(fx);
        assert(fy > 4.99);
        assert(fy < 5.01);

        dx = 25;
        dy = sqrt(dx);
        assert(dy > 4.99);
        assert(dy < 5.01);

        fx = 8;
        fy = sqrt(fx);
        assert(fy > 2.8);
        assert(fy < 2.9);

        dx = 8;
        dy = sqrt(dx);
        assert(dy > 2.8);
        assert(dy < 2.9);
        return 0;
}
```

**Comment by ukasz** [comment]
Tested on (581618e829), out of the four test cases posted earlier, the last two are failing at this point.

**Comment by ukasz** [comment]
Seems that we have a regression again on devel branch and tests which were passing are now broken.
Example:
```
volatile float a = 0.199;
volatile float b = 0.2;
assert(a < b);
assert(a <= b);
assert(b > a);
assert(b >= a);
a = 0.2;
assert(a == b);
```

**Comment by donofrio** [comment]
Revisiting this issue... The test above appears to be working properly, however, the `testPi()` function appears to still fail. I believe the root cause of this is a double to single precision conversion that Rev is performing incorrectly - will address and have a fix ASAP

**Comment by ukasz** [comment]
This bug has become a container for multiple things. I believe it is not a good idea to track it this way. Original issue has been fixed so I am closing this bug and we'll create simpler self-contained issues with more specific problems.
