### ISSUE TITLE
Memory test fails on 2 byte accesses

### ISSUE THREAD

**Issue by ukasz** [tactcomplabs/rev#55]
The following code fails on rev-devel (tested sha: cd753f7c)
The same test works fine with 1,4,8 byte wide accesses.
```
#include <stdio.h>
#define u16 unsigned short
#define u8 unsigned char
#define assert(x) if (!(x)) { asm(".byte 0x00"); asm(".byte 0x00"); asm(".byte 0x00"); asm(".byte 0x00"); }

/*
 * Write 0 to a memory, hammer down ones around it,
 * check that it is still 0 at the end.
 */

#define hammer(type) int hammer_##type(type *addr, size_t size) { \
        int ret = 0; \
        type ff = (type)0xffffffffffff; \
        for (size_t i = 2; i < size - 2; i++) { \
                addr[i] = 0; \
                for (size_t j = 0; j < 10; j++) { \
                        addr[i - 1] = ff; \
                        addr[i - 2] = ff; \
                        addr[i + 1] = ff; \
                        addr[i + 2] = ff; \
                } \
                ret |= (addr[i] != 0);  \
        } \
        return ret; \
}

hammer(u16)

int test_3(void *addr, size_t size) {
        int ret = 0;

        ret |= hammer_u16(addr, size / 2);
        return ret;
}

/* Memory to test */
#define SIZE 10000
u8 mem[SIZE];

int main(){
        assert(!test_3(mem, SIZE));
}
```

**Comment by ukasz** [comment]
Slightly different test case, which is also failing only on 2 byte data size:
`
#include <stdio.h>
#define u16 unsigned short
#define u8 unsigned char
#define assert(x) if (!(x)) { asm(".byte 0x00"); asm(".byte 0x00"); asm(".byte 0x00"); asm(".byte 0x00"); }

/* Memory to test */
#define SIZE 10000
u8 mem[SIZE];

#define fill_stride_f(type) void fill_stride_by_##type(type *addr, size_t size, type pattern, size_t idx, size_t stride) \
{ \
        for (size_t i = idx; i < size; i += stride) \
                addr[i] = pattern; \
}

fill_stride_f(u16);

#define check_stride_f(type) int check_stride_by_##type(type *addr, size_t size, size_t idx, type pattern, size_t stride) \
{ \
        int ret  = 0; \
        for (size_t i = idx; i < size; i += stride) \
                ret |= (addr[i] != pattern); \
        return ret;\
}

check_stride_f(u16);

int main(){
        u16 *addr =(u16*) mem;
        size_t size = SIZE/sizeof(u16);
        int ret = 0;
        const size_t stride = 16;

        for (size_t idx = 0; idx < stride; idx++) {
                fill_stride_by_u16((u16*)addr, size / 2, idx, idx, stride);
                ret |= check_stride_by_u16((u16*)addr, size / 2, idx, idx, stride);
        }
        assert(!ret);
        return 0;
}

`

**Comment by donofrio** [comment]
Both of these tests should now work correctly in the latest devel branch

**Comment by ukasz** [comment]
I tried test/memset_2 on (4414659) and it is still failing for me.
